function Arc(a,b,c){this.p1=a;this.p2=b;this.a=(c?c:90)*Math.PI/180;this._P={o:this,pos:function(){return{x:this.o.cx,y:this.o.cy}},moveBy:function(a,b){var c=this.o.p1.pos(),g=this.o.p2.pos(),k=g.x-c.x,g=g.y-c.y,c=.5*Math.sqrt(k*k+g*g),k=c*Math.tan(.5*(Math.PI-this.o.a))-(g*a-k*b)/c*.5;this.o.a=2*Math.atan2(c,k)},GetId:function(){return""+Main.GetId(this.o)+".0"},draw:function(a,b){a.strokeStyle=this._s&2?"#FF0000":"#000000";var c=this.pos();(0<b||this._s&2)&&a.strokeRect(c.x-2,c.y-2,5,5)}};a&&this.Update()}
Arc.prototype={ctor:"Arc",dep:["p1","p2"],serialize:function(){return Items.indexOf(this.p1).toString()+","+Items.indexOf(this.p2)+","+180*this.a/Math.PI},toJSON:function(a){return{p1:Main.GetId(this.p1),p2:Main.GetId(this.p2),a:180*this.a/Math.PI,_:"Arc"}},OnLoad:function(){this.a*=Math.PI/180;return this.p1&&this.p2},child:function(a){return this._P},Update:function(){var a=this.p1.pos(),b=this.p2.pos(),c=.5*(b.x-a.x),d=.5*(b.y-a.y),e=1/Math.tan(.5*this.a),f=c-d*e,c=d+c*e;this.cx=a.x+f;this.cy=
a.y+c;this.R=Math.sqrt(f*f+c*c);this.a1=Math.atan2(-c,-f);this.a2=Math.atan2(b.y-this.cy,b.x-this.cx)},draw:function(a,b){var c=this.color?this.color:css.def;a.strokeStyle=b&2?css.sel:b&1?css.touch:c;a.lineWidth=1;a.beginPath();this.Update();a.arc(this.cx,this.cy,this.R,this.a1,this.a2);a.stroke();(this._s&2||0<b)&&this._P.draw(a,1)},hp:8,hit:function(a,b,c){this.Update();var d=this._P.pos();if(Math.abs(d.x-a)<c&&Math.abs(d.y-b)<c)return this._P;a-=this.cx;b-=this.cy;if(Math.abs(Math.sqrt(a*a+b*b)-
this.R)>c)return null;c=Math.atan2(b,a);return this.a2>this.a1?c>this.a2||c<this.a1?null:this:c>this.a2&&c<this.a1?null:this},rHit:function(a,b,c,d){var e=this.p1.pos(),f=this.p2.pos();return e.x>a&&e.y>b&&e.x<c&&e.y<d&&f.x>a&&f.y>b&&f.x<c&&f.y<d},vec:function(a){var b=a.pos();return a===this.p1?{x:(this.cy-b.y)/this.R,y:(b.x-this.cx)/this.R}:a===this.p2?{x:(b.y-this.cy)/this.R,y:(this.cx-b.x)/this.R}:null},moveBy:function(a,b){this._s&4||(this.p1.moveBy(a,b),this.p2.moveBy(a,b),this._s|=4)}};
(function(a,b,c,d){var e=null,f=null,g=Point,k=Arc,m=a.active,l=b.states.free.move;a.ctors.Arc=Arc;var n={draw:function(a){f.draw(a,1)},move:function(a,b){l(a,b);var d=c.mo;d&&d.pos?(d=d.pos(),e.x=d.x,e.y=d.y):(e.x=a,e.y=b);return!0},leftup:function(a,b){var h;h=c.mo;c.pointAlign&&h&&h.pos?(rfa(f.p2._der,f),f.p2=h=c.mo,pd(h,f)):m.push(h=e);m.push(f);e=new g(a,b);f=new k(h,e);d.needRedraw=!0;d.needFast=!0},rightup:function(){b.pop();return!0}},p={move:l,leftup:function(a,d){var h,l=c.mo;c.pointAlign&&
l&&l.pos?h=l:m.push(h=new g(a,d));e=new g(a,d);f=new k(h,e);b.go(n)},rightup:b.pop};CMenu.Add({create:{_:{label:"\u0414\u0443\u0433\u0443",click:function(){b.call(p)}}}})})(storage,ctl,editor,view);function Arrow(a){this.ps=a;this._s=0}
Arrow.prototype={ctor:"Arrow",dep:["ps"],draw:function(a,b){if(!(2>this.ps.length)){var c=this.color?this.color:css.def;a.strokeStyle=b&2?css.sel:b&1?css.touch:c;a.beginPath();a.lineWidth=2;var d=this.ps[0].pos();a.moveTo(d.x,d.y);for(var e=this.ps.length,c=1;c<e;c++)d=this.ps[c].pos(),a.lineTo(d.x,d.y);var d=this.ps[e-1].pos(),c=d.x,f=d.y,d=this.ps[e-2].pos(),e=c-d.x,d=f-d.y,g=Math.sqrt(e*e+d*d)/3;0<g&&(e/=g,d/=g,a.moveTo(c-3*e-d,f-3*d+e),a.lineTo(c,f),a.lineTo(c-3*e+d,f-3*d-e));a.stroke();this.label&&
(d=this.ps[0].pos(),this.x&&(d.x+=+this.x),this.y&&(d.y+=+this.y),a.font=Main.font,a.textBaseline="top",a.fillStyle="#000000",a.fillText(this.label,d.x,d.y))}},moveBy:function(a,b){if(!(this._s&4)){for(var c in this.ps)this.ps[c].moveBy(a,b);this._s|=4}},hp:8,hit:function(a,b){var c=this.ps[0].pos();if(this.label){var d=(this.y?+this.y:0)+c.y;if((this.x?+this.x:0)+c.x<a&&d<b&&d+10>b&&(ctx.font=Main.font,d+ctx.measureText(this.label).width>b))return this._lp={o:this,moveBy:function(a,b){this.o.x+=
a;this.o.y+=b},draw:function(a){a=this.o.ps[0].pos();if("number"!==typeof this.o.x||"number"!==typeof this.o.y)this.o.y=0,this.o.x=0;a.x+=this.o.x;a.y+=this.o.y;ctx.lineWidth=.5;ctx.strokeRect(a.x,a.y+1,ctx.measureText(this.o.label).width,11)}}}for(var d=0,e=this.ps.length-1;d<e;d++){var f=c,c=this.ps[d+1].pos();if(!(a-3>f.x&&a-3>c.x||b-3>f.y&&b-3>c.y||a+3<f.x&&a+3<c.x||b+3<f.y&&b+3<c.y)){var g=c.x-f.x,k=c.y-f.y,f=g*(b-f.y)-k*(a-f.x),g=Math.sqrt(g*g+k*k),f=f/g;if(3>Math.abs(f))return this}}return null},
GetPSel:function(){if(this._s&2)return!0;for(var a=0,b=this.ps.length;a<b;a++)if(this.ps[a]._s&2)return!0;return!1},onDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",update:Main.Redraw,data:{label:"\u041c\u0435\u0442\u043a\u0430",x:"\u041c\u0435\u0442\u043a\u0430, X",y:"\u041c\u0435\u0442\u043a\u0430, Y"}},this)}};
(function(a,b,c,d){var e=null,f=null,g=Point,k=Arrow;a.ctors.Arrow=k;var m=a.active,l=b.states.free.move,n={draw:function(a){f.draw(a,1)},move:function(a,b){l(a,b);var f=c.mo;f&&f.pos?(f=f.pos(),e.x=f.x,e.y=f.y):(e.x=a,e.y=b);d.needFast=!0},leftup:function(a,b){var d=c.mo;if(c.pointAlign&&d&&d.pos){var k=f.ps;k[k.length-1]=d}else m.push(e),e=new g(a,b);f.ps.push(e)},rightup:function(a,c){f.ps.pop();1<f.ps.length?m.push(f):m.pop();e=f=null;b.pop();d.needRedraw=!0;d.needFast=!0}},p={move:l,leftup:function(a,
d){var h,l=c.mo;c.pointAlign&&l&&l.pos?h=l:m.push(h=new g(a,d));e=new g(a,d);f=new k([h,e]);b.go(n)},rightup:b.pop};CMenu.Add({create:{_:{label:"\u0421\u0442\u0440\u0435\u043b\u043a\u0443",click:function(){b.call(p);"undefined"!==typeof CToolbar&&CToolbar.cancel.show(!0)}}}})})(storage,ctl,editor,view);function Block(a){for(c in a)a.hasOwnProperty(c)&&(this[c]=a[c]);this._P=[{pos:function(){return{x:this.o.x,y:this.o.y}},moveBy:function(a,b){this.o.x+=a;this.o.y+=b;this.o.w-=a;this.o.h-=b}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y}},moveBy:function(a,b){this.o.w+=a;this.o.y+=b;this.o.h-=b}},{pos:function(){return{x:this.o.x,y:this.o.y+this.o.h}},moveBy:function(a,b){this.o.x+=a;this.o.h+=b;this.o.w-=a}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y+this.o.h}},moveBy:function(a,
b){this.o.w+=a;this.o.h+=b}},{pos:function(){return{x:this.o.x+this.o.w/2,y:this.o.y}},moveBy:function(a,b){this.o.y+=b;this.o.h-=b}},{pos:function(){return{x:this.o.x+this.o.w/2,y:this.o.y+this.o.h}},moveBy:function(a,b){this.o.h+=b}},{pos:function(){return{x:this.o.x,y:this.o.y+this.o.h/2}},moveBy:function(a,b){this.o.x+=a;this.o.w-=a}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y+this.o.h/2}},moveBy:function(a,b){this.o.w+=a}}];this.exps=[];a=function(a,b){a.strokeStyle=this._sel?"#FF0000":
"#000000";var c=this.pos();if(0<b||this._sel)a.lineWidth=1,a.strokeRect(c.x-2,c.y-2,4,4)};for(var b=function(){return""+Items.indexOf(this.o)+"."+this.x},c=this._P.length-1;0<=c;c--)this._P[c].o=this,this._P[c].x=c,this._P[c].draw=a,this._P[c].GetId=b;this.text&&(this.text=this.text.split("\n"));this.child=function(a){return this._P[a]};this.OnLoad=function(a){return this.x&&this.y&&this.w&&this.h?!0:!1}}
Block.prototype={toJSON:function(){var a={_:"Block"},b;for(b in this)this.hasOwnProperty(b)&&"_"!==b.charAt(0)&&(a[b]=this[b]);return a},hit:function(a,b,c){for(var d=this._P.length-1;0<=d;d--){var e=this._P[d].pos();if(Math.abs(e.x-a)<c&&Math.abs(e.y-b)<c)return this._P[d]}if(a<this.x||a>this.x+this.w||b<this.y||b>this.y+this.h)return null;if(this.text&&(c=this.text,d=this.getTextLayout(),b=Math.floor((b-d.y)/d.dy),a=Math.floor((a-d.x)/d.dx),0<=a&&0<=b&&b<c.length&&a<c[b].length)){c=c[b];d=/\w/;
if(!d.test(c.charAt(a)))return this;for(e=a;0<e&&d.test(c.charAt(e-1));)e--;for(a+=1;a<c.length&&d.test(c.charAt(a));)a++;a--;b={o:this,x:e,l:a-e+1,y:b,draw:function(a,b){var c=this.o.getTextLayout(),d=c.x+this.x*c.dx,e=c.y+this.y*c.dy;a.lineWidth=1;a.strokeStyle="#000";a.strokeRect(d,e+1,this.l*c.dx,c.dy+1)},pos:function(){var a=this.o.getTextLayout();return{x:a.x+(this.x+this.l)*a.dx,y:a.y+(this.y+1)*a.dy+2}}};this.exps.push(b);return b}return this},OnOk:function(){var a=document.getElementById("blocktext");
this.text=void 0;""!==a.value&&(this.text=a.value.split("\n"));hideBlockDialog()},moveBy:function(a,b){if(!(this._s&4)){this.x+=a;this.y+=b;for(var c in this._P)this._P[c]._s|=4}},setFontSize:function(a,b){this.fsize=b;this._font=b.toString()+"px monospace";this._dx=a.measureText("X").width},getTextLayout:function(){var a=this.fsize;return{x:this.x+a,y:this.y+.5*this.h-(this.text?this.text.length:0)*a/2,dx:this._dx,dy:a}},draw:function(a,b){a.lineWidth=1;a.strokeStyle="#000";a.fillStyle=this._sel?
"#FFE0E0":"#FFFFFF";this.type&&"if"===this.type?(a.beginPath(),a.moveTo(this.x,this.y+this.h/2),a.lineTo(this.x+this.w/2,this.y),a.lineTo(this.x+this.w,this.y+this.h/2),a.lineTo(this.x+this.w/2,this.y+this.h),a.closePath(),a.fill(),a.stroke()):(a.fillRect(this.x,this.y,this.w,this.h),a.strokeRect(this.x,this.y,this.w,this.h));if(this.text){var c=this.getTextLayout(),d=c.x,e=c.y;a.textBaseline="top";a.fillStyle="#000000";a.font=this._font;var f,g;f=0;for(g=this.text.length;f<g;f++,e+=c.dy)a.fillText(this.text[f],
d,e)}if(this._sel||0<b)for(f=this._P.length;f--;)this._P[f].draw(a,1);c=0;for(f in this.exps)g=this.exps[f],g===MouseObject?this.exps[c++]=g:g._der&&0<g._der.length&&(g.draw(a,0),this.exps[c++]=g);this.exps.length=c},autoSize:function(a){a.font=this._font;var b=this.text.length,c=this.getTextLayout();this.h=(b+1)*c.dy;for(var d=10,e=0;e<b;e++){var f=a.measureText(this.text[e]).width;f>d&&(d=f)}this.w=d+2*(c.x-this.x)},onDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",
update:Main.Redraw,data:{text:{name:"\u0422\u0435\u043a\u0441\u0442",tag:"textarea"},type:{name:"\u0422\u0438\u043f",options:[""]},x:"X",y:"Y",w:"\u0428\u0438\u0440\u0438\u043d\u0430",h:"\u0412\u044b\u0441\u043e\u0442\u0430"}},this)}};
(function(a,b,c,d){var e=null,f=Block,g=a.active,k=b.states.free.move;a.ctors.Block=f;var m={draw:function(a){e.draw(a,1)},move:function(a,b){k(a,b);if(e.x+e.w!=a||e.y+e.h!=b)e.w=a-e.x,e.h=b-e.y,d.needFast=!0},leftup:function(a,c){0>e.w&&(e.x+=e.w,e.w=-e.w);0>e.h&&(e.y+=e.h,e.h=-e.h);g.push(e);b.pop()},rightup:function(){b.pop();d.needRedraw=!0;d.needFast=!0}},l={move:k,leftup:function(a,d){var g;g=c.mo;c.pointAlign&&g&&g.pos?(g=g.pos(),e=new f({x:g.x,y:g.y,w:1,h:1})):e=new f({x:a,y:d,w:1,h:1});b.go(m)},
rightup:b.pop};CMenu.Add({create:{_:{label:"\u0411\u043b\u043e\u043a",click:function(){b.call(l)}}}})})(storage,ctl,editor,view);function Point(a,b){this.x=a;this.y=b;this._der=[];this._s=0}
Point.prototype={toJSON:function(){return{_:"Point",x:this.x,y:this.y}},pos:function(){return{x:this.x,y:this.y}},draw:function(a,b){a.strokeStyle=this._sel?"#FF0000":css.color;if(0<b||this._sel||!this._der.length)a.lineWidth=1,a.strokeRect(this.x-2,this.y-2,4,4)},moveBy:function(a,b){this._s&4||(this.x+=a,this.y+=b,this._s|=4,this.Owner&&this.Owner.OnPtMoveBy(this,a,b))},hp:10,hit:function(a,b,c){a=Math.abs(this.x-a);b=Math.abs(this.y-b);return a<c&&b<c?this:null},rHit:function(a,b,c,d){return a<
this.x&&b<this.y&&c>this.x&&d>this.y},OnDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",update:Main.Redraw,data:{x:"X",y:"Y"}},this)},GetPSel:function(){return this._sel}};function Line(a,b){this.p1=a;this.p2=b;"object"===typeof a&&pd(a,this);"object"===typeof b&&pd(b,this);this._s=0}
Line.prototype={ctor:"Line",dep:["p1","p2"],draw:function(a,b){var c=this.color?this.color:css.def;a.strokeStyle=b&2?css.sel:b&1?css.touch:c;a.lineWidth=this.width?this.width:.5;a.beginPath();c=this.p1.pos();a.moveTo(c.x,c.y);c=this.p2.pos();a.lineTo(c.x,c.y);a.stroke()},moveBy:function(a,b){this._s&4||(this.p1.moveBy(a,b),this.p2.moveBy(a,b),this._s|=4)},hp:8,hit:function(a,b,c){var d=this.p1.pos(),e=this.p2.pos(),f=a-c,g=b-c;if(f>d.x&&f>e.x||g>d.y&&g>e.y)return null;f=a+c;g=b+c;if(f<d.x&&f<e.x||
g<d.y&&g<e.y)return null;f=e.x-d.x;e=e.y-d.y;a=f*(b-d.y)-e*(a-d.x);b=Math.sqrt(f*f+e*e);return Math.abs(a/b)<c?this:null},rHit:function(a,b,c,d){var e=this.p1.pos(),f=this.p2.pos();return e.x>a&&e.y>b&&e.x<c&&e.y<d&&f.x>a&&f.y>b&&f.x<c&&f.y<d},setP2:function(a){RemoveFromArray(this.p2._der,this);this.p2=a;PushDer(a,this)},setP1:function(a){RemoveFromArray(this.p1._der,this);this.p1=a;PushDer(a,this)},del:function(){RemoveFromArray(this.p1._der,this);RemoveFromArray(this.p2._der,this)},vec:function(a){var b=
this.p1.pos(),c=this.p2.pos(),d=c.x-b.x,b=c.y-b.y,c=Math.sqrt(d*d+b*b);1E-9<c&&(d/=c,b/=c);if(a===this.p1)return{x:d,y:b};if(a===this.p2)return{x:-d,y:-b}},GetPSel:function(){return this._sel||this.p1._sel||this.p2._sel}};
(function(a,b,c,d){var e=null,f=null,g=Line,k=Point;a.ctors.Point=k;a.ctors.Line=g;var m=a.active,l=b.states.free.move,n={draw:function(a){f.draw(a,1)},move:function(a,b){l(a,b);var d=c.mo;d&&d.pos?(d=d.pos(),e.x=d.x,e.y=d.y):(e.x=a,e.y=b);return!0},leftup:function(a,b){var h;h=c.mo;c.pointAlign&&h&&h.pos?(rfa(f.p2._der,f),f.p2=h=c.mo,pd(h,f)):m.push(h=e);m.push(f);e=new k(a,b);f=new g(h,e);d.needRedraw=!0},rightup:function(){b.pop();return!0}},p={move:l,leftup:function(a,d){var h,l=c.mo;c.pointAlign&&
l&&l.pos?h=l:m.push(h=new Point(a,d));e=new k(a,d);f=new g(h,e);b.go(n)},rightup:b.pop};CMenu.Add({create:{_:{label:"\u041b\u0438\u043d\u0438\u044e",click:function(){b.call(p);"undefined"!==typeof CToolbar&&CToolbar.cancel.show(!0)}}}})})(storage,ctl,editor,view);
