// Generated by CoffeeScript 1.8.0
var StorageCtl;

StorageCtl = function($scope, $location) {
  $scope.location = $location;
  $scope.sheets = storage.data.sheets;
  $scope.newSheet = function(name) {
    return storage.data.sheets.push({
      name: name,
      items: []
    });
  };
  $scope.removeSheet = function(sheet) {
    return rfa(storage.data.sheets, sheet);
  };
  $scope.isSel = function(sheet) {
    return sheet.items === storage.active;
  };
  $scope.select = function(sheet) {
    storage.active = sheet.items;
    return ctl.update();
  };
  $scope.clear = function(name) {
    storage.data.sheets.length = 0;
    $scope.newSheet(name);
    storage.active = storage.data.sheets[0].items;
    return ctl.update();
  };
  $scope["import"] = function() {
    return imp();
  };
  return $scope.save = function(name) {
    var json;
    return json = storage.getJSON();
  };
};
