// Generated by CoffeeScript 1.8.0
(function() {
  var Workarea;

  Workarea = function(canvas, fast) {
    var ctl, editor, view;
    view = new View(canvas, fast);
    view.seq.push(view.clear);
    ctl = new Controller(view, window);
    editor = new Editor(storage, view, ctl);
    if (typeof Navi !== "undefined" && Navi !== null) {
      Navi(view, ctl);
    }
    if (typeof Grid !== "undefined" && Grid !== null) {
      view.grid = new Grid(view, editor);
      view.seq.push(view.grid.draw);
    }
    view.seq.push(editor.draw);
    return window.onload = function() {
      return window.onresize();
    };
  };

}).call(this);
