function Arc(a,c,b){this.p1=a;this.p2=c;this.a=b*Math.PI/180;this._P={o:this,pos:function(){return{x:this.o.cx,y:this.o.cy}},moveBy:function(a,b){var c=this.o.p1.pos(),g=this.o.p2.pos(),h=g.x-c.x,g=g.y-c.y,c=.5*Math.sqrt(h*h+g*g),h=c*Math.tan(.5*(Math.PI-this.o.a))-(g*a-h*b)/c*.5;this.o.a=2*Math.atan2(c,h)},GetId:function(){return""+Main.GetId(this.o)+".0"},draw:function(a){ctx.strokeStyle=this._sel?"#FF0000":"#000000";var b=this.pos();(0<a||this._sel)&&ctx.strokeRect(b.x-2,b.y-2,5,5)}};a&&this.Update()}
Arc.prototype={ctor:"Arc",dep:["p1","p2"],serialize:function(){return Items.indexOf(this.p1).toString()+","+Items.indexOf(this.p2)+","+180*this.a/Math.PI},toJSON:function(a){return{p1:Main.GetId(this.p1),p2:Main.GetId(this.p2),a:180*this.a/Math.PI,_:"Arc"}},OnLoad:function(){this.a*=Math.PI/180;return this.p1&&this.p2},child:function(a){return this._P},Update:function(){var a=this.p1.pos(),c=this.p2.pos(),b=.5*(c.x-a.x),d=.5*(c.y-a.y),f=1/Math.tan(.5*this.a),e=b-d*f,b=d+b*f;this.cx=a.x+e;this.cy=
a.y+b;this.R=Math.sqrt(e*e+b*b);this.a1=Math.atan2(-b,-e);this.a2=Math.atan2(c.y-this.cy,c.x-this.cx)},draw:function(a,c){a.strokeStyle=this._sel?"#FF0000":0<c?"#808080":"#000000";a.lineWidth=1;a.beginPath();this.Update();a.arc(this.cx,this.cy,this.R,this.a1,this.a2);a.stroke();(this._sel||0<c)&&this._P.draw(1)},Hit:function(a,c){if(1>=Main.hitPriority)return null;this.Update();var b=this._P.pos(),d=Main.adm;if(Math.abs(b.x-a)<d&&Math.abs(b.y-c)<d)return this._P;var b=a-this.cx,f=c-this.cy;if(Math.abs(Math.sqrt(b*
b+f*f)-this.R)>d)return null;d=Math.atan2(f,b);return this.a2>this.a1?d>this.a2||d<this.a1?null:this:d>this.a2&&d<this.a1?null:this},RHit:function(a,c,b,d){var f=this.p1.pos(),e=this.p2.pos();return f.x>a&&f.y>c&&f.x<b&&f.y<d&&e.x>a&&e.y>c&&e.x<b&&e.y<d},vec:function(a){var c=a.pos();return a===this.p1?{x:(this.cy-c.y)/this.R,y:(c.x-this.cx)/this.R}:a===this.p2?{x:(c.y-this.cy)/this.R,y:(this.cx-c.x)/this.R}:null},moveBy:function(a,c){this._mov||(this.p1.moveBy(a,c),this.p2.moveBy(a,c),this._mov=
!0)}};
var CArc={Pt:null,Obj:null,MainRedraw:null,Redraw:function(a){CArc.MainRedraw(a);CArc.Obj.draw(a,1)},OnCreate:function(){Main.Call(States.prearc)},OnInit:function(){Main.Ctors.Arc=Arc;States.prearc={move:function(a,c){Main.PointAlign?Main.OnAlignedMove(a,c):Main.OnFreeMove(a,c)},leftup:function(a,c){CArc.MainRedraw=State.redraw;var b;Main.PointAlign&&MouseObject&&MouseObject.pos?b=MouseObject:Items.push(b=new Point(Main.MX,Main.MY));CArc.Pt=new Point(Main.MX,Main.MY);CArc.Obj=new Arc(b,CArc.Pt,90);
Main.Goto(States.nxarc)},rightup:Main.Pop};States.nxarc={redraw:CArc.Redraw,move:function(a,c){Main.PointAlign?Main.OnAlignedMove(a,c):Main.OnFreeMove(a,c);if(CArc.Pt.x!=Main.MX||CArc.Pt.y!=Main.MY)Main.NeedRedraw=!0,CArc.Pt.x=Main.MX,CArc.Pt.y=Main.MY},leftup:function(a,c){var b;Main.PointAlign&&MouseObject&&MouseObject.pos?CArc.Obj.p2=b=MouseObject:Items.push(b=CArc.Pt);Items.push(CArc.Obj);CArc.Pt=new Point(Main.MX,Main.MY);CArc.Obj=new Arc(b,CArc.Pt,90)},rightup:Main.Pop};CMenu.Add({create:{_:{label:"\u0414\u0443\u0433\u0443",
click:this.OnCreate}}})},menu:[{path:"createmenu",label:"\u0414\u0443\u0433\u0443",click:null}]};Main.Modules.push(CArc);function Arrow(a){this.ps=a;this._s=0}
Arrow.prototype={ctor:"Arrow",dep:["ps"],draw:function(a,c){if(!(2>this.ps.length)){var b=this.color?this.color:css.def;a.strokeStyle=c&2?css.sel:c&1?css.touch:b;a.beginPath();a.lineWidth=2;var d=this.ps[0].pos();a.moveTo(d.x,d.y);for(var f=this.ps.length,b=1;b<f;b++)d=this.ps[b].pos(),a.lineTo(d.x,d.y);var d=this.ps[f-1].pos(),b=d.x,e=d.y,d=this.ps[f-2].pos(),f=b-d.x,d=e-d.y,g=Math.sqrt(f*f+d*d)/3;0<g&&(f/=g,d/=g,a.moveTo(b-3*f-d,e-3*d+f),a.lineTo(b,e),a.lineTo(b-3*f+d,e-3*d-f));a.stroke();this.label&&
(d=this.ps[0].pos(),this.x&&(d.x+=+this.x),this.y&&(d.y+=+this.y),a.font=Main.font,a.textBaseline="top",a.fillStyle="#000000",a.fillText(this.label,d.x,d.y))}},moveBy:function(a,c){if(!(this._s&4)){for(var b in this.ps)this.ps[b].moveBy(a,c);this._s|=4}},hp:8,hit:function(a,c){var b=this.ps[0].pos();if(this.label){var d=(this.y?+this.y:0)+b.y;if((this.x?+this.x:0)+b.x<a&&d<c&&d+10>c&&(ctx.font=Main.font,d+ctx.measureText(this.label).width>c))return this._lp={o:this,moveBy:function(a,b){this.o.x+=
a;this.o.y+=b},draw:function(a){a=this.o.ps[0].pos();if("number"!==typeof this.o.x||"number"!==typeof this.o.y)this.o.y=0,this.o.x=0;a.x+=this.o.x;a.y+=this.o.y;ctx.lineWidth=.5;ctx.strokeRect(a.x,a.y+1,ctx.measureText(this.o.label).width,11)}}}for(var d=0,f=this.ps.length-1;d<f;d++){var e=b,b=this.ps[d+1].pos();if(!(a-3>e.x&&a-3>b.x||c-3>e.y&&c-3>b.y||a+3<e.x&&a+3<b.x||c+3<e.y&&c+3<b.y)){var g=b.x-e.x,h=b.y-e.y,e=g*(c-e.y)-h*(a-e.x),g=Math.sqrt(g*g+h*h),e=e/g;if(3>Math.abs(e))return this}}return null},
GetPSel:function(){if(this._s&2)return!0;for(var a=0,c=this.ps.length;a<c;a++)if(this.ps[a]._s&2)return!0;return!1},onDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",update:Main.Redraw,data:{label:"\u041c\u0435\u0442\u043a\u0430",x:"\u041c\u0435\u0442\u043a\u0430, X",y:"\u041c\u0435\u0442\u043a\u0430, Y"}},this)}};
(function(a,c,b,d){var f=null,e=null,g=Point,h=Arrow;a.ctors.Arrow=h;var l=a.active,k=c.states.free.move,n={draw:function(a){e.draw(a,1)},move:function(a,c){k(a,c);var e=b.mo;e&&e.pos?(e=e.pos(),f.x=e.x,f.y=e.y):(f.x=a,f.y=c);d.needFast=!0},leftup:function(a,c){var d=b.mo;if(b.pointAlign&&d&&d.pos){var h=e.ps;h[h.length-1]=d}else l.push(f),f=new g(a,c);e.ps.push(f)},rightup:function(a,b){e.ps.pop();1<e.ps.length?l.push(e):l.pop();f=e=null;c.pop();d.needRedraw=!0;d.needFast=!0}},m={move:k,leftup:function(a,
d){var k,m=b.mo;b.pointAlign&&m&&m.pos?k=m:l.push(k=new g(a,d));f=new g(a,d);e=new h([k,f]);c.go(n)},rightup:c.pop};CMenu.Add({create:{_:{label:"\u0421\u0442\u0440\u0435\u043b\u043a\u0443",click:function(){c.call(m);"undefined"!==typeof CToolbar&&CToolbar.cancel.show(!0)}}}})})(storage,ctl,editor,view);function Block(a){this.setFontSize(ctx,10);for(b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);this._P=[{pos:function(){return{x:this.o.x,y:this.o.y}},moveBy:function(a,b){this.o.x+=a;this.o.y+=b;this.o.w-=a;this.o.h-=b}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y}},moveBy:function(a,b){this.o.w+=a;this.o.y+=b;this.o.h-=b}},{pos:function(){return{x:this.o.x,y:this.o.y+this.o.h}},moveBy:function(a,b){this.o.x+=a;this.o.h+=b;this.o.w-=a}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y+
this.o.h}},moveBy:function(a,b){this.o.w+=a;this.o.h+=b}},{pos:function(){return{x:this.o.x+this.o.w/2,y:this.o.y}},moveBy:function(a,b){this.o.y+=b;this.o.h-=b}},{pos:function(){return{x:this.o.x+this.o.w/2,y:this.o.y+this.o.h}},moveBy:function(a,b){this.o.h+=b}},{pos:function(){return{x:this.o.x,y:this.o.y+this.o.h/2}},moveBy:function(a,b){this.o.x+=a;this.o.w-=a}},{pos:function(){return{x:this.o.x+this.o.w,y:this.o.y+this.o.h/2}},moveBy:function(a,b){this.o.w+=a}}];this.exps=[];a=function(a,b){a.strokeStyle=
this._sel?"#FF0000":"#000000";var c=this.pos();if(0<b||this._sel)a.lineWidth=1,a.strokeRect(c.x-2,c.y-2,4,4)};for(var c=function(){return""+Items.indexOf(this.o)+"."+this.x},b=this._P.length-1;0<=b;b--)this._P[b].o=this,this._P[b].x=b,this._P[b].draw=a,this._P[b].GetId=c;this.text&&(this.text=this.text.split("\n"));this.child=function(a){return this._P[a]};this.OnLoad=function(a){return this.x&&this.y&&this.w&&this.h?!0:!1}}
Block.prototype={toJSON:function(){var a={_:"Block"},c;for(c in this)this.hasOwnProperty(c)&&"_"!==c.charAt(0)&&(a[c]=this[c]);return a},Hit:function(a,c){for(var b=this._P.length-1;0<=b;b--){var d=this._P[b].pos();if(3>Math.abs(d.x-a)&&3>Math.abs(d.y-c))return this._P[b]}if(a<this.x||a>this.x+this.w||c<this.y||c>this.y+this.h)return null;if(this.text){var f=this.text,d=this.getTextLayout(),b=Math.floor((c-d.y)/d.dy),d=Math.floor((a-d.x)/d.dx);if(0<=d&&0<=b&&b<f.length&&d<f[b].length){var f=f[b],
e=/\w/;if(!e.test(f.charAt(d)))return this;for(var g=d;0<g&&e.test(f.charAt(g-1));)g--;for(d+=1;d<f.length&&e.test(f.charAt(d));)d++;d--;b={o:this,x:g,l:d-g+1,y:b,draw:function(a,b){var c=this.o.getTextLayout(),d=c.x+this.x*c.dx,e=c.y+this.y*c.dy;a.lineWidth=1;a.strokeStyle="#000";a.strokeRect(d,e+1,this.l*c.dx,c.dy+1)},pos:function(){var a=this.o.getTextLayout();return{x:a.x+(this.x+this.l)*a.dx,y:a.y+(this.y+1)*a.dy+2}}};this.exps.push(b);return b}}return this},OnOk:function(){var a=document.getElementById("blocktext");
this.text=void 0;""!==a.value&&(this.text=a.value.split("\n"));hideBlockDialog()},moveBy:function(a,c){if(!this._mov){this.x+=a;this.y+=c;for(var b in this._P)this._P[b]._mov=!0}},setFontSize:function(a,c){this.fsize=c;this._font=c.toString()+"px monospace";this._dx=a.measureText("X").width},getTextLayout:function(){var a=this.fsize;return{x:this.x+a,y:this.y+.5*this.h-(this.text?this.text.length:0)*a/2,dx:this._dx,dy:a}},draw:function(a,c){a.lineWidth=1;a.strokeStyle="#000";a.fillStyle=this._sel?
"#FFE0E0":"#FFFFFF";this.type&&"if"===this.type?(a.beginPath(),a.moveTo(this.x,this.y+this.h/2),a.lineTo(this.x+this.w/2,this.y),a.lineTo(this.x+this.w,this.y+this.h/2),a.lineTo(this.x+this.w/2,this.y+this.h),a.closePath(),a.fill(),a.stroke()):(a.fillRect(this.x,this.y,this.w,this.h),a.strokeRect(this.x,this.y,this.w,this.h));if(this.text){var b=this.getTextLayout(),d=b.x,f=b.y;a.textBaseline="top";a.fillStyle="#000000";a.font=this._font;var e,g;e=0;for(g=this.text.length;e<g;e++,f+=b.dy)a.fillText(this.text[e],
d,f)}if(this._sel||0<c)for(e=this._P.length;e--;)this._P[e].draw(a,1);b=0;for(e in this.exps)g=this.exps[e],g===MouseObject?this.exps[b++]=g:g._der&&0<g._der.length&&(g.draw(a,0),this.exps[b++]=g);this.exps.length=b},autoSize:function(a){a.font=this._font;var c=this.text.length,b=this.getTextLayout();this.h=(c+1)*b.dy;for(var d=10,f=0;f<c;f++){var e=a.measureText(this.text[f]).width;e>d&&(d=e)}this.w=d+2*(b.x-this.x)},onDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",
update:Main.Redraw,data:{text:{name:"\u0422\u0435\u043a\u0441\u0442",tag:"textarea"},type:{name:"\u0422\u0438\u043f",options:[""]},x:"X",y:"Y",w:"\u0428\u0438\u0440\u0438\u043d\u0430",h:"\u0412\u044b\u0441\u043e\u0442\u0430"}},this)}};
var CBlock={MainRedraw:null,Obj:null,OnCreate:function(){Main.Call(States.preblock)},OnInit:function(){Main.Ctors.Block=Block;States.preblock={move:function(a,c){Main.PointAlign?Main.OnAlignedMove(a,c):Main.OnFreeMove(a,c)},leftup:function(a,c){CBlock.MainRedraw=State.redraw;var b;Main.PointAlign&&MouseObject&&MouseObject.pos?(b=MouseObject.pos(),CBlock.Obj=new Block({x:b.x,y:b.y,w:1,h:1})):CBlock.Obj=new Block({x:Main.MX,y:Main.MY,w:1,h:1});Main.Goto(States.nxblock)},rightup:Main.Pop};States.nxblock=
{redraw:function(a){CBlock.MainRedraw(a);CBlock.Obj.draw(a,1)},move:function(a,c){Main.PointAlign?Main.OnAlignedMove(a,c):Main.OnFreeMove(a,c);if(CBlock.Obj.x+CBlock.Obj.w!=Main.MX||CBlock.Obj.y+CBlock.Obj.h!=Main.MY)Main.NeedRedraw=!0,CBlock.Obj.w=Main.MX-CBlock.Obj.x,CBlock.Obj.h=Main.MY-CBlock.Obj.y},leftup:function(a,c){var b=CBlock.Obj;0>b.w&&(b.x+=b.w,b.w=-b.w);0>b.h&&(b.y+=b.h,b.h=-b.h);Items.push(b);Main.Pop()}};CMenu.Add({create:{_:{label:"\u0411\u043b\u043e\u043a",click:this.OnCreate}}})}};
Main.Modules.push(CBlock);function Point(a,c){this.x=a;this.y=c;this._der=[];this._s=0}
Point.prototype={toJSON:function(){return{_:"Point",x:this.x,y:this.y}},pos:function(){return{x:this.x,y:this.y}},draw:function(a,c){a.strokeStyle=this._sel?"#FF0000":css.color;if(0<c||this._sel||!this._der.length)a.lineWidth=1,a.strokeRect(this.x-2,this.y-2,4,4)},moveBy:function(a,c){this._s&4||(this.x+=a,this.y+=c,this._s|=4,this.Owner&&this.Owner.OnPtMoveBy(this,a,c))},hp:10,hit:function(a,c,b){a=Math.abs(this.x-a);c=Math.abs(this.y-c);return a<b&&c<b?this:null},rHit:function(a,c,b,d){return a<
this.x&&c<this.y&&b>this.x&&d>this.y},OnDblClick:function(){Dialogs&&Dialogs.Create({title:"\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430",update:Main.Redraw,data:{x:"X",y:"Y"}},this)},GetPSel:function(){return this._sel}};function Line(a,c){this.p1=a;this.p2=c;"object"===typeof a&&pd(a,this);"object"===typeof c&&pd(c,this);this._s=0}
Line.prototype={ctor:"Line",dep:["p1","p2"],draw:function(a,c){var b=this.color?this.color:css.def;a.strokeStyle=c&2?css.sel:c&1?css.touch:b;a.lineWidth=this.width?this.width:.5;a.beginPath();b=this.p1.pos();a.moveTo(b.x,b.y);b=this.p2.pos();a.lineTo(b.x,b.y);a.stroke()},moveBy:function(a,c){this._s&4||(this.p1.moveBy(a,c),this.p2.moveBy(a,c),this._s|=4)},hp:8,hit:function(a,c,b){var d=this.p1.pos(),f=this.p2.pos(),e=a-b,g=c-b;if(e>d.x&&e>f.x||g>d.y&&g>f.y)return null;e=a+b;g=c+b;if(e<d.x&&e<f.x||
g<d.y&&g<f.y)return null;e=f.x-d.x;f=f.y-d.y;a=e*(c-d.y)-f*(a-d.x);c=Math.sqrt(e*e+f*f);return Math.abs(a/c)<b?this:null},rHit:function(a,c,b,d){var f=this.p1.pos(),e=this.p2.pos();return f.x>a&&f.y>c&&f.x<b&&f.y<d&&e.x>a&&e.y>c&&e.x<b&&e.y<d},setP2:function(a){RemoveFromArray(this.p2._der,this);this.p2=a;PushDer(a,this)},setP1:function(a){RemoveFromArray(this.p1._der,this);this.p1=a;PushDer(a,this)},del:function(){RemoveFromArray(this.p1._der,this);RemoveFromArray(this.p2._der,this)},vec:function(a){var c=
this.p1.pos(),b=this.p2.pos(),d=b.x-c.x,c=b.y-c.y,b=Math.sqrt(d*d+c*c);1E-9<b&&(d/=b,c/=b);if(a===this.p1)return{x:d,y:c};if(a===this.p2)return{x:-d,y:-c}},GetPSel:function(){return this._sel||this.p1._sel||this.p2._sel}};
(function(a,c,b,d){var f=null,e=null;a.ctors.Point=Point;a.ctors.Line=Line;var g=a.active,h=c.states.free.move,l={draw:function(a){e.draw(a,1)},move:function(a,c){h(a,c);var e=b.mo;e&&e.pos?(e=e.pos(),f.x=e.x,f.y=e.y):(f.x=a,f.y=c);d.needFast=!0},leftup:function(a,c){var h;h=b.mo;b.pointAlign&&h&&h.pos?(rfa(e.p2._der,e),e.p2=h=b.mo,pd(h,e)):g.push(h=f);g.push(e);f=new Point(a,c);e=new Line(h,f);d.needRedraw=!0;d.needFast=!0},rightup:function(){c.pop();d.needFast=!0}},k={move:h,leftup:function(a,d){var h,
k=b.mo;b.pointAlign&&k&&k.pos?h=k:g.push(h=new Point(a,d));f=new Point(a,d);e=new Line(h,f);c.go(l)},rightup:c.pop};CMenu.Add({create:{_:{label:"\u041b\u0438\u043d\u0438\u044e",click:function(){c.call(k);"undefined"!==typeof CToolbar&&CToolbar.cancel.show(!0)}}}})})(storage,ctl,editor,view);
